language: node_js
node_js:
    - 10
deploy:
    provider: npm
    email: git@technicallyjosh.com
    skip_cleanup: true
    api_key:
        secure: f+J6y+1sKO0zRT4V8O32FGSegcNXQK9QyUbmqZXV/sgZH1wjKOwWTVyLWlgTYSsa8srUWSdC2OQao0WKk/lq3wYUWQ5U5h3WK6akbet57S1eKMgXhc+z9IGYrIvSyeYSuG7xcZP+qA2Lt8XLsCuitaFSmOqNhdBb+AdIETvtlM9nUj2u0e9bswpqFHINZPN9s4DwjcMcQJ6QfCyE29e0Zgssxb5mOqqpwB3FCkE4+Hk3oz0H86TWAT/blyIt63VZbMyg2jTzG6OO5cBBUNz4RAKzVjUxg120DlWC8zkrBki8JMwE3pnxsOirEtgeS+3HYk1bP6w7n4YGJPp6rVaz/dXTvqI/9XTIh75G0kVERL4JYOIRXyWNbPqULo0eilrpXjzJYsEMYBSqcWjY4ib8xB2IBw33nGDfFTDQN2n/syXeWirVTwW0BI17cXZSHtiNshH6C98XZKstKOBUSK0vPA+3XKEsVOrBA1SPChfgE6UsOypKpb2c7VL3pbgFgsAxFfA4Z8xlMoTPvpfMasgwpMcJERqYOr4FQp1JyKV7rkqmk6jAq98d8JGYKPhrwZtZd8U5uSNzD3HsU8uo0TbxhQDa9iiijSjbzNZGPqGtHimhHJTV2Cs48CsDaQhiOPH+lVtyJNgsKPYtYXFZzBJMNIukM+kE2JcyLLz/F22ssm4=
    on:
        tags: true
        repo: technicallyjosh/koa-fluent-validation
